### ISSUE TITLE
java.lang.IndexOutOfBoundsException when mutating ConstValue Constraints

### ISSUE THREAD

**Issue by mayerkr** [viatra/cps-model-generator#14]
## Description:
java.lang.IndexOutOfBoundsException when mutating ConstValue Constraints

## Log:
```
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at org.eclipse.viatra.dslreasoner.patternmutator.PatternMutator$HelperPQuery.copyBody(PatternMutator.java:473)
	at org.eclipse.viatra.dslreasoner.patternmutator.PatternMutator$HelperPQuery.copyPQuery(PatternMutator.java:546)
	at org.eclipse.viatra.dslreasoner.patternmutator.PatternMutator$HelperPQuery.<init>(PatternMutator.java:100)
	at org.eclipse.viatra.dslreasoner.patternmutator.PatternMutator.mutate(PatternMutator.java:897)
	at org.eclipse.viatra.dslreasoner.patternmutator.Run.main(Run.java:31)
```

**Comment by mayerkr** [comment]
Currently the mutation of ConstValue Constraints is disabled.
